### ISSUE TITLE
Error while processing route: user.add Ember Data Request GET

### ISSUE THREAD

**Issue by IZulz** [88sparesinternship/inventory#4]
![screenshot 2](https://user-images.githubusercontent.com/39718158/45139163-7d22f100-b1e1-11e8-9521-7764694c61b2.png)
![screenshot 3](https://user-images.githubusercontent.com/39718158/45139164-7dbb8780-b1e1-11e8-8b0c-2ee736f9f689.png)
![screenshot 4](https://user-images.githubusercontent.com/39718158/45139165-7dbb8780-b1e1-11e8-8cc2-eab9c32f054f.png)
![screenshot 5](https://user-images.githubusercontent.com/39718158/45139166-7e541e00-b1e1-11e8-98df-efe62467d635.png)

**Comment by paperlambda** [comment]
udah dicek firebase koneksi sama modelnya?

**Comment by paperlambda** [comment]
Ditutup ya, masalahnya karena lupa install package `emberfire`. untuk install emberfire, pake `ember install emberfire`
