### ISSUE TITLE
Nothing handled the action 'deleteUser'

### ISSUE THREAD

**Issue by IZulz** [88sparesinternship/inventory#6]
![screenshot 6](https://user-images.githubusercontent.com/39718158/45419818-e9f32b00-b6ba-11e8-9ed2-8ecb55ee538a.png)
![screenshot 7](https://user-images.githubusercontent.com/39718158/45419819-e9f32b00-b6ba-11e8-995b-345769b1452f.png)
![screenshot 8](https://user-images.githubusercontent.com/39718158/45419820-e9f32b00-b6ba-11e8-9a1f-ac564bae0dc9.png)

"Nothing handled the action 'deleteUser'. If you did handle the action, this error can be caused by returning true from an action handler in a controller, causing the action to bubble."

**Comment by paperlambda** [comment]
coba liat lg itu actionsnya ada di add.js tp dipanggil di user.hbs

**Comment by paperlambda** [comment]
udah bisa? @IZulz
