### ISSUE TITLE
cara dapatin ember-simple-auth

### ISSUE THREAD

**Issue by rahbar81** [88sparesinternship/inventory#7]
![screenshot 40](https://user-images.githubusercontent.com/40995697/45470546-5ec87280-b758-11e8-88e8-d515d1f975e7.png)

Kak biar dapet kaya gini gimana caranya  ka??
contoh    "ember-simple-auth": "1.0.0";
di package.json

**Comment by paperlambda** [comment]
cek https://github.com/simplabs/ember-simple-auth
