### ISSUE TITLE
Cannot find module 'glob'

### ISSUE THREAD

**Issue by rahbar81** [88sparesinternship/inventory#8]
![screenshot 41](https://user-images.githubusercontent.com/40995697/45475050-70fcdd80-b765-11e8-9984-ef4a12afb894.png)

kak, maksud dari Cannot find module 'glob' apasi ka?
rahbar udah serch trus nemu, npm install --save glob -g 
pas rahbar ember serve lagi munculnya  Cannot find module 'glob' ,lagi kaa

**Comment by paperlambda** [comment]
`npm install --save glob -g` itu nginstall module namanya `glob` sedangkan itu ga ada di npm package. `-g` itu untuk install di PC secara global jadi ga perlu lagi `glob` nya. sekarang uninstall dlu pake `npm uninstall --save glob` trus `ember serve`

**Comment by rahbar81** [comment]
sudah rahbar uninstall kak, pas rahbar serve lagi masih  Cannot find module 'glob' kak

**Comment by paperlambda** [comment]
cari tempat scriptnya dipanggil
